### ISSUE TITLE
Update third-party actions we use to latest to get rid of Node.js 16 deprecation warning (OSOE-710)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/GitHub-Actions#272]
Since Node.js 16 has reached its end of life, [GitHub is deprecating it too](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). Because of this, you may see warnings like this under workflow runs:

![image](https://github.com/Lombiq/GitHub-Actions/assets/1976647/3899e8ab-5d00-4153-8ca2-91a2061e86d1)

We need to update all the third-party actions if and when they fix this to get rid of the warnings. Affected actions:

- [x] https://github.com/actions/checkout: Already updated.
- [x] https://github.com/actions/cache: https://github.com/actions/cache/issues/1260. However, this also affects https://github.com/BuildJet/cache where https://github.com/BuildJet/cache/issues/1 needs to be done.
- [x] https://github.com/actions/setup-dotnet: Needs https://github.com/actions/setup-dotnet/issues/478.
- [x] https://github.com/actions/upload-artifact: Needs https://github.com/actions/upload-artifact/issues/444. Also create an internal wrapper action like we have for `checkout` so we can manage it centrally, and update the reference to use the new action.
- [x] https://github.com/phoenix-actions/test-reporting: Needs https://github.com/phoenix-actions/test-reporting/issues/43.
- [x] https://github.com/buildsville/add-remove-label: Needs https://github.com/buildsville/add-remove-label/issues/7.
- [x] https://github.com/azure/login: Needs https://github.com/Azure/login/issues/357.
- [x] https://github.com/Azure/webapps-deploy: Needs https://github.com/Azure/webapps-deploy/issues/372 (and https://github.com/Azure/webapps-deploy/issues/392, which is a duplicate).
- [x] https://github.com/check-spelling/check-spelling: Needs https://github.com/check-spelling/check-spelling/issues/63. - This will need to be done later, one it's released, as part of https://github.com/Lombiq/GitHub-Actions/issues/353.

Check out the release notes of all of these, since there might be breaking changes (like for `actions/upload-artifact`).

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-710)

**Comment by Piedone** [comment]
Related: https://github.com/Lombiq/GitHub-Actions/issues/275.

**Comment by Piedone** [comment]
Let's start this ASAP, then without `check-spelling` if it still won't be released until then.
